services:
  ForumDataBase:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=ForumDataBase'
      - 'POSTGRES_PASSWORD=mnbvc'
      - 'POSTGRES_USER=admin'
    volumes:
      - './import:/docker-entrypoint-initdb.d:ro'
    ports:
      - '6000:5432'
